options:
  auto-update: true
  debug: false
lang:
   token-use: "&aYou have successfully used this %token%!"
   token-deny: "&fYou are unable to use this %token%!"
   player-first-join: 
      - "&6Welcome %player_name% to the server!"
   player-welcome-back:
      - "&6Welcome back, %player_name%!"
   player-motd:
      - "&6Welcome back, %player_name%!"
      - "&4If you lost your experience generator, please open a ticket on our discord server."
machines:
   experience-generator:
      energy-per-tick: 150
      energy-capacity: 2000
      experience-per-tick: 0.5
      max-experience-held: 2000
   quantum-server:
   automatic-sieve:
      
   block-breaker:
      blacklisted-items:

spawning:
  virulean_zombie:
    spawn_chance: 1    #1% chance to spawn when a hostile mob spawns. Double, so supports 0.00001 etc.
    blacklisted_dimensions:
      - world_nether
      - world_the_end
  
  
  
  
tokens:
   basic:
      name: "&7Basic Research Token"
      desc: "&7>> &4&nRight-Click&r &7to redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber
   advanced:
      name: "&eAdvanced Research Token"
      desc: "&e>> &4&nRight-Click&r &eto redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber
   elite:
      name: "&aElite Research Token"
      desc: "&a>> &4&nRight-Click&r &ato redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber
   legendary:
      name: "&6Legendary Research Token"
      desc: "&6>> &4&nRight-Click&r &6to redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber