options:
  auto-update: true
  debug: false
lang:
   token-use: "&aYou have successfully used this %token%!"
   token-deny: "&fYou are unable to use this %token%!"
   player-first-join: 
      - "&6Welcome %player_name% to the server!"
   player-welcome-back:
      - "&6Welcome back, %player_name%!"
machines:
   experience-generator:
      energy-per-tick: 100
      energy-capacity: 2000
      experience-per-tick: 0.02
      max-experience-held: 1000
   quantum-server:
   automatic-sieve:
      
   block-breaker:
      blacklisted-items:
         - 
  
tokens:
   basic:
      name: "&7Basic Research Token"
      desc: "&7>> &4&nRight-Click&r &7to redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber
   advanced:
      name: "&eAdvanced Research Token"
      desc: "&e>> &4&nRight-Click&r &eto redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber
   elite:
      name: "&aElite Research Token"
      desc: "&a>> &4&nRight-Click&r &ato redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber
   legendary:
      name: "&6Legendary Research Token"
      desc: "&6>> &4&nRight-Click&r &6to redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber