options:
  auto-update: true
  debug: false
lang:
   token-use: "&aYou have successfully used this %token%!"
   token-deny: "&fYou are unable to use this %token%!"
   player-first-join: 
      - "&a&lWelcome %player_name% to the server!"
   player-welcome-back:
      - "&6Welcome back, %player_name%!"
   player-motd:
      - "&6&l&nWelcome, %player_name%!"
      - "&e&lIf you encounter a bug, please open a ticket on our discord server."
      - "&e&n( https://discord.gg/wNA3FfXSPg )"
machines:
   experience-generator:
      energy-per-tick: 150
      energy-capacity: 2000
      experience-per-tick: 0.5
      max-experience-held: 2000

spawning:
   virulean_zombie:
      spawn_chance: 500
      blacklisted_dimensions:
         - world_nether
         - world_the_end
   wandering_sword:
      spawn_chance: 500
      blacklisted_dimensions:
         - world_nether
         - world_the_end  
tokens:
   basic:
      name: "&7Basic Research Token"
      desc: "&7>> &4&nRight-Click&r &7to redeem this token."
      unlocks: 
         - slimefun:basic_circuit_board
         - slimefun:smeltery 
         - slimefun:steel
         - slimefun:battery
         - slimefun:slimefun_metals
         - slimefun:ore_crusher
         - slimefun:alloys
         - slimefun:compressor_and_carbon
         - slimefun:pressure_chamber
         - slimefun:magic_workbench
         - slimefun:crushed_ore
         - slimefun:nickel_and_cobalt
         - slimefun:high_tier_advanced_furnaces
         - slimefun:reinforced_furnace
         - slimefun:carbonado_furnace
         - slimefun:block_placer
         - slimefun:enhanced_furnace
         - slimefun:juicer
         - slimefun:ancient_altar
         - slimefun:automatic_ignition_chamber
   advanced:
      name: "&eAdvanced Research Token"
      desc: "&e>> &4&nRight-Click&r &eto redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber
   elite:
      name: "&aElite Research Token"
      desc: "&a>> &4&nRight-Click&r &ato redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber
   legendary:
      name: "&6Legendary Research Token"
      desc: "&6>> &4&nRight-Click&r &6to redeem this token."
      unlocks: 
         - slimefun:automatic_ignition_chamber